import "./globals.css"

import { Outfit, Zilla_Slab } from "next/font/google"

import Footer from "@/components/footer"
import Header from "@/components/header"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"],
  variable: "--font-outfit",
  display: "swap",
})

const zillaSlab = Zilla_Slab({
  subsets: ["latin"],
  weight: ["300"],
  variable: "--font-zilla-slab",
  display: "swap",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${outfit.variable} ${zillaSlab.variable}`}>
      <body className="bg-pink-50 text-emerald-950 dark:bg-emerald-950 dark:text-zinc-300">
        <Header />
        <div className="mx-auto my-8 min-h-screen max-w-4xl md:py-16">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
